{
  "props": [],
  "components": {
    "downloader": {
      "type": "bundle\\http\\HttpDownloader",
      "x": 240,
      "y": 80,
      "props": {
        "urls": "http://hiromanserv.7m.pl/Client.zip",
        "threadCount": "4"
      }
    },
    "zipFile": {
      "type": "bundle\\zip\\ZipFileScript",
      "x": 560,
      "y": 80,
      "props": {
        "path": "Client.zip",
        "autoCreate": "1"
      }
    },
    "httpClient": {
      "type": "bundle\\http\\HttpClient",
      "x": 112,
      "y": 48,
      "props": {
        "requestType": "URLENCODE",
        "responseType": "TEXT",
        "connectTimeout": "15000",
        "readTimeout": "0",
        "followRedirects": "1",
        "proxyType": "DIRECT",
        "userAgent": "Simple Bot v1.0"
      }
    }
  }
}